In [3]:
import torch
a = torch.rand(2,3)
b = torch.rand(2,3)
print("a:\n",a)
print("b:\n",b)
print("a+b:\n",a+b)

b.add(a)
print("add:\n",b.add(a))
print("b:\n",b)
print("")

print("add_:\n",b.add_(a))
print("b:\n",b)

a:
 tensor([[0.8387, 0.5755, 0.1188],
        [0.8813, 0.6266, 0.0367]])
b:
 tensor([[0.3065, 0.1949, 0.4205],
        [0.0219, 0.2026, 0.4831]])
a+b:
 tensor([[1.1452, 0.7705, 0.5393],
        [0.9032, 0.8291, 0.5198]])
add:
 tensor([[1.1452, 0.7705, 0.5393],
        [0.9032, 0.8291, 0.5198]])
b:
 tensor([[0.3065, 0.1949, 0.4205],
        [0.0219, 0.2026, 0.4831]])

add_:
 tensor([[1.1452, 0.7705, 0.5393],
        [0.9032, 0.8291, 0.5198]])
b:
 tensor([[1.1452, 0.7705, 0.5393],
        [0.9032, 0.8291, 0.5198]])


## 获取大小

In [8]:
import torch
a = torch.rand(4,5)
print(a)
print(a.size())
print(a.shape)
print("")

print("The first row:\n",a[0,:])
print("The third col:\n",a[:,2])

tensor([[0.0290, 0.4257, 0.6223, 0.3764, 0.7471],
        [0.9541, 0.6205, 0.3415, 0.7945, 0.9092],
        [0.8704, 0.3845, 0.0880, 0.1960, 0.5689],
        [0.3270, 0.7636, 0.1450, 0.4438, 0.2238]])
torch.Size([4, 5])
torch.Size([4, 5])

The first row:
 tensor([0.0290, 0.4257, 0.6223, 0.3764, 0.7471])
The third col:
 tensor([0.6223, 0.3415, 0.0880, 0.1450])


## 改变形状

In [10]:
x = torch.rand(4,5)
print(x.size())

y = x.clone().view(20)
print(y.size())

y = x.clone().view(-1,10)
print(y.size())

y = x.clone().view(10,-1)
print(y.size())

torch.Size([4, 5])
torch.Size([20])
torch.Size([2, 10])
torch.Size([10, 2])


## 广播机制

In [11]:
x = torch.arange(1,3).view(1,2)
y = torch.arange(1,4).view(3,1)
print("x:\n",x)
print("y:\n",y)
print("x+y:\n",torch.add(x,y))

x:
 tensor([[1, 2]])
y:
 tensor([[1],
        [2],
        [3]])
x+y:
 tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 连接

In [12]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
print("X:\n",X)
print("Y:\n",Y)
res1 = torch.cat((X,Y),dim=0)
res2 = torch.cat((X,Y),dim=1)
print("accroding tor row:\n",res1)
print("accroding tor col:\n",res2)

X:
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Y:
 tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
accroding tor row:
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
accroding tor col:
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


## 内存开销

In [14]:
x = torch.arange(1,3)
y = torch.arange(2,4)
id_before = id(y)

print(id(y))#1961734599520
y = y+x
print(id(y))#1961734601840

y[:] = y+x
print(id(y))#1961734601840

torch.add(x,y,out=y)
print(id(y)) #1961734601840
print(id_before)

1961734599520
1961734601840
1961734601840
1961734601840
1961734599520
